-- 演示模式数据库结构（H2，PostgreSQL 兼容模式）
-- 生产环境使用 db/init.sql（PostgreSQL + pgvector）

CREATE TABLE IF NOT EXISTS school (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    region      VARCHAR(100),
    level       VARCHAR(20),
    type        VARCHAR(20),
    status      SMALLINT DEFAULT 1,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone         VARCHAR(20) UNIQUE,
    password      VARCHAR(100),
    nickname      VARCHAR(50),
    role          VARCHAR(20) DEFAULT 'TEACHER',
    school_id     BIGINT,
    status        SMALLINT DEFAULT 1,
    last_login_at TIMESTAMP,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teacher_profile (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL,
    subjects       VARCHAR(255),
    grades         VARCHAR(255),
    teaching_years SMALLINT,
    weak_network   BOOLEAN DEFAULT FALSE,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS class_group (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id  BIGINT NOT NULL,
    grade      VARCHAR(20),
    class_name VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id   BIGINT NOT NULL,
    name       VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student_score (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    subject    VARCHAR(30),
    score      NUMERIC(5,1),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kb_document (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(200) NOT NULL,
    doc_type         VARCHAR(30) NOT NULL,
    user_id          BIGINT,
    subject          VARCHAR(30),
    grade            VARCHAR(20),
    textbook_version VARCHAR(50),
    status           SMALLINT DEFAULT 1,
    meta             CLOB,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kb_chunk (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id    BIGINT NOT NULL,
    seq       INT,
    content   CLOB NOT NULL,
    metadata  CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prompt_template (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene       VARCHAR(50) NOT NULL,
    subject     VARCHAR(30),
    lesson_type VARCHAR(30),
    version     INT DEFAULT 1,
    content     CLOB NOT NULL,
    config      CLOB,
    status      SMALLINT DEFAULT 1,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS generation_task (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    scene         VARCHAR(30) DEFAULT 'LESSON_PLAN',
    params        CLOB,
    provider      VARCHAR(30),
    status        VARCHAR(20) DEFAULT 'PENDING',
    error_message CLOB,
    cost_cents    INT DEFAULT 0,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lesson_plan (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id       BIGINT,
    user_id       BIGINT NOT NULL,
    title         VARCHAR(200),
    subject       VARCHAR(30),
    grade         VARCHAR(20),
    textbook      VARCHAR(100),
    lesson_type   VARCHAR(30),
    content       CLOB,
    quality_score SMALLINT,
    is_public     SMALLINT DEFAULT 0,
    status        SMALLINT DEFAULT 1,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lesson_section (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_plan_id BIGINT NOT NULL,
    section_type   VARCHAR(30),
    seq            INT,
    content        CLOB,
    standard_ref   VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS exercise (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_plan_id  BIGINT,
    task_id         BIGINT,
    subject         VARCHAR(30),
    grade           VARCHAR(20),
    knowledge_point VARCHAR(100),
    difficulty      VARCHAR(10),
    type            VARCHAR(20),
    content         CLOB,
    answer          CLOB,
    analysis        CLOB
);

CREATE TABLE IF NOT EXISTS usage_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT,
    school_id    BIGINT,
    action       VARCHAR(50),
    scene        VARCHAR(30),
    duration_sec INT,
    cost_cents   INT,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS feedback (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT,
    lesson_plan_id BIGINT,
    type           VARCHAR(20),
    content        CLOB,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS survey (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id  BIGINT,
    round      VARCHAR(20),
    teacher_id BIGINT,
    metric     VARCHAR(50),
    metric_value NUMERIC(10,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS model_config (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider       VARCHAR(30),
    model          VARCHAR(50),
    api_key_cipher VARCHAR(255),
    enabled        BOOLEAN DEFAULT TRUE,
    priority       INT,
    note           VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS content_review_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      BIGINT,
    content_type VARCHAR(30),
    result       VARCHAR(20),
    detail       CLOB,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO school (id, name, region, level, type) VALUES (1, '演示学校-新乡某乡村小学', '新乡市', '小学', '公办');
INSERT INTO sys_user (id, phone, password, nickname, role, school_id, status)
VALUES (1, '13800000000', '123456', '演示教师', 'TEACHER', 1, 1);

-- 知识库种子：课标 / 教材 / 模板 / 乡土案例
INSERT INTO kb_document (id, title, doc_type, subject, grade, textbook_version, status)
VALUES (1, '2022版义务教育语文课程标准·核心素养与学习任务群', 'STANDARD', '语文', NULL, NULL, 1);
INSERT INTO kb_document (id, title, doc_type, subject, grade, textbook_version, status)
VALUES (2, '2022版义务教育数学课程标准·三会与内容领域', 'STANDARD', '数学', NULL, NULL, 1);
INSERT INTO kb_document (id, title, doc_type, subject, grade, textbook_version, status)
VALUES (3, '2022版义务教育英语课程标准·核心素养与内容六要素', 'STANDARD', '英语', NULL, NULL, 1);
INSERT INTO kb_document (id, title, doc_type, subject, grade, textbook_version, status)
VALUES (4, '新授课教案通用模板', 'TEMPLATE', NULL, NULL, NULL, 1);
INSERT INTO kb_document (id, title, doc_type, subject, grade, textbook_version, status)
VALUES (5, '人教版语文八年级上册·教材目录', 'TEXTBOOK', '语文', '八年级', '人教版', 1);
INSERT INTO kb_document (id, title, doc_type, subject, grade, textbook_version, status)
VALUES (6, '河南新乡乡土案例库', 'CASE', NULL, NULL, NULL, 1);

INSERT INTO kb_chunk (doc_id, seq, content) VALUES (1, 1, '语文核心素养：文化自信、语言运用、思维能力、审美创造。学习任务群：语言文字积累与梳理、实用性阅读与交流、文学阅读与创意表达、思辨性阅读与表达、整本书阅读、跨学科学习。');
INSERT INTO kb_chunk (doc_id, seq, content) VALUES (2, 1, '数学核心素养三会：会用数学的眼光观察现实世界，会用数学的思维思考现实世界，会用数学的语言表达现实世界。内容领域：数与代数、图形与几何、统计与概率、综合与实践。');
INSERT INTO kb_chunk (doc_id, seq, content) VALUES (3, 1, '英语核心素养：语言能力、文化意识、思维品质、学习能力。课程内容六要素：主题、语篇、语言知识、文化知识、语言技能、学习策略。');
INSERT INTO kb_chunk (doc_id, seq, content) VALUES (4, 1, '教案结构：教学目标（素养导向）→ 教学重难点 → 教学准备 → 教学过程（导入/新授/互动/练习/总结，每环节标注时间与师生活动）→ 板书设计 → 分层作业（基础/提高/拓展）→ 课后反思。');
INSERT INTO kb_chunk (doc_id, seq, content) VALUES (5, 1, '人教版语文八年级上册目录：第一单元 活动探究·新闻；第二单元 回忆性散文（藤野先生、回忆我的母亲、列夫·托尔斯泰、美丽的颜色）；第三单元 古诗文（三峡、短文二篇、与朱元思书、唐诗五首）；第四单元 散文（背影、白杨礼赞、散文二篇、昆明的雨）；第五单元 说明文（中国石拱桥、苏州园林、蝉、梦回繁华）；第六单元 古诗文（孟子二章、愚公移山、周亚夫军细柳、诗词五首）。');
INSERT INTO kb_chunk (doc_id, seq, content) VALUES (6, 1, '新乡乡土素材：中原农谷国家级农业科技平台；牧野大地麦收文化（三夏抢收）；封丘陈桥驿（宋太祖黄袍加身处）；辉县百泉；新乡南太行（万仙山、八里沟）；毗邻红旗渠精神（林州）；豫剧、河南坠子等非遗；平原新区黄河滩区生态治理。可用于情境导入与跨学科教学。');

INSERT INTO prompt_template (scene, subject, lesson_type, version, content, status)
VALUES ('LESSON_PLAN', NULL, NULL, 1,
        '你是资深中小学教研专家，依据2022版义务教育课程标准，严格围绕用户提供的【课题】生成完整教案，禁止偏离课题。输出严格的 JSON 格式（字段：title, subject, grade, textbook, lessonType, objectives[{type,content,standardRef}], keyPoints[], difficultPoints[], process[{stage,duration,activities,teacher,student}], boardDesign, homework[{level,items[]}], qualityScore, standardCards[{ref,content}]）。要求：1) title 与课题一致；2) 教学目标对应核心素养且必须与课题直接相关；3) 教学过程标注环节与时长，总计约40/45分钟；4) 板书设计与课题匹配；5) 作业为分层作业（基础/提高/拓展）；6) standardCards 必须给出课标依据并引用真实课标条目；7) 全部字段必须填充真实内容，禁止空数组、空字符串。只输出 JSON，不要输出任何其他文字。',
        1);

-- 演示教案（《背影》第一课时，供编辑器与图表展示）
INSERT INTO lesson_plan (id, task_id, user_id, title, subject, grade, textbook, lesson_type, content, quality_score, is_public, status)
VALUES (1, NULL, 1, '《背影》第一课时', '语文', '八年级', '人教版', '新授课',
        '{"objectives":[{"type":"文化自信","content":"感受经典散文的语言魅力，体悟中华民族孝亲敬长的传统美德。","standardRef":"课标·语文·文学阅读与创意表达"},{"type":"语言运用","content":"积累「蹒跚」「颓唐」等词语，学习抓住人物特征进行描写。","standardRef":"课标·语文·语言文字积累与梳理"},{"type":"思维能力","content":"通过四次「背影」的分析，理解散文「形散神聚」的特点。","standardRef":"课标·语文·思辨性阅读与表达"}],"keyPoints":["四次「背影」的描写及其作用"],"difficultPoints":["结合时代背景理解父子情感的变化"],"process":[{"stage":"情境导入","duration":5,"activities":"播放《父亲》歌曲片段，提问：你印象最深的父亲的背影是什么？"},{"stage":"初读感知","duration":8,"activities":"自由朗读课文，梳理文章结构，概括四次背影出现的场景。"},{"stage":"精读背影","duration":15,"activities":"聚焦「望父买橘」片段，品析动作描写，体会父爱；结合1925年写作背景理解作者情感变化。"},{"stage":"小组讨论","duration":10,"activities":"讨论：为什么「我的眼泪又来了」？结合生活分享亲情故事。"},{"stage":"总结作业","duration":7,"activities":"总结「背影」的线索作用，布置分层作业。"}],"boardDesign":"背影\n├ 难忘背影（回忆）\n├ 望父买橘（刻画）\n├ 惜别背影（抒情）\n└ 再现背影（升华）","homework":[{"level":"基础","items":["积累本课生字词并抄写"]},{"level":"提高","items":["以「我的父亲/母亲」为题写300字片段，运用动作描写"]},{"level":"拓展","items":["阅读《荷塘月色》，对比两篇文章的语言风格"]}],"qualityScore":92,"standardCards":[{"ref":"课标·语文·文学阅读与创意表达","content":"阅读叙事类作品，能把握主要内容，理解人物形象，体会作者情感。"}]}',
        92, 1, 1);

INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (1, 'OBJECTIVE', 0, '{"type":"文化自信","content":"感受经典散文的语言魅力，体悟中华民族孝亲敬长的传统美德。","standardRef":"课标·语文·文学阅读与创意表达"}', '课标·语文·文学阅读与创意表达');
INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (1, 'OBJECTIVE', 1, '{"type":"语言运用","content":"积累「蹒跚」「颓唐」等词语，学习抓住人物特征进行描写。","standardRef":"课标·语文·语言文字积累与梳理"}', '课标·语文·语言文字积累与梳理');
INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (1, 'PROCESS', 2, '{"stage":"情境导入","duration":5,"activities":"播放《父亲》歌曲片段，提问：你印象最深的父亲的背影是什么？"}', NULL);

-- 数学：一元二次方程 九年级
INSERT INTO lesson_plan (id, task_id, user_id, title, subject, grade, textbook, lesson_type, content, quality_score, is_public, status)
VALUES (2, NULL, 1, '一元二次方程', '数学', '九年级', '人教版', '新授课',
        '{"objectives":[{"type":"会用数学的眼光观察现实世界","content":"理解一元二次方程的概念，能识别一元二次方程及其一般形式。","standardRef":"课标·数学·数与代数·方程与不等式"},{"type":"会用数学的思维思考现实世界","content":"通过实际问题抽象为一元二次方程的过程，体会建模思想。","standardRef":"课标·数学·综合与实践·问题解决"},{"type":"会用数学的语言表达现实世界","content":"能将实际问题转化为一元二次方程的一般形式，确定各项系数。","standardRef":"课标·数学·数与代数·符号意识"}],"keyPoints":["一元二次方程的概念及一般形式ax2+bx+c=0(a≠0)"],"difficultPoints":["从实际问题中抽象出一元二次方程模型，理解a≠0的条件"],"process":[{"stage":"情境导入","duration":5,"activities":"展示校园面积扩建问题：正方形花坛边长增加2m后面积变为36m2，求原边长。"},{"stage":"概念探究","duration":10,"activities":"对比一元一次方程，归纳一元二次方程的三个特征：一个未知数、最高次数2、整式方程。"},{"stage":"一般形式","duration":12,"activities":"推导ax2+bx+c=0(a≠0)，强调a≠0的必要性，识别二次项、一次项、常数项及系数。"},{"stage":"例题练习","duration":10,"activities":"完成3道判断一元二次方程并化为一般形式的练习，小组互评。"},{"stage":"总结作业","duration":3,"activities":"梳理概念要点，布置分层作业。"}],"boardDesign":"一元二次方程\n├ 概念：一个未知数、最高次数2、整式方程\n├ 一般形式：ax²+bx+c=0 (a≠0)\n│  ├ 二次项 ax²  系数a\n│  ├ 一次项 bx   系数b\n│  └ 常数项 c\n└ 建模：实际问题 → 设未知数 → 列方程 → 一般形式","homework":[{"level":"基础","items":["教材P28 习题21.1 第1-2题"]},{"level":"提高","items":["将方程3x(x-1)=2(x+2)化为一般形式，并指出各项系数"]},{"level":"拓展","items":["编一道可用一元二次方程解决的生活实际问题"]}],"qualityScore":90,"standardCards":[{"ref":"课标·数学·数与代数","content":"能根据具体问题中的数量关系列出方程，体会方程是刻画现实世界数量关系的有效模型。"}]}',
        90, 1, 1);

INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (2, 'OBJECTIVE', 0, '{"type":"会用数学的眼光观察现实世界","content":"理解一元二次方程的概念，能识别一元二次方程及其一般形式。","standardRef":"课标·数学·数与代数·方程与不等式"}', '课标·数学·数与代数·方程与不等式');
INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (2, 'OBJECTIVE', 1, '{"type":"会用数学的思维思考现实世界","content":"通过实际问题抽象为一元二次方程的过程，体会建模思想。","standardRef":"课标·数学·综合与实践·问题解决"}', '课标·数学·综合与实践·问题解决');
INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (2, 'PROCESS', 2, '{"stage":"概念探究","duration":10,"activities":"对比一元一次方程，归纳一元二次方程的三个特征。"}', NULL);

-- 英语：Unit 1 My name's Gina 七年级
INSERT INTO lesson_plan (id, task_id, user_id, title, subject, grade, textbook, lesson_type, content, quality_score, is_public, status)
VALUES (3, NULL, 1, 'Unit 1 My name''s Gina (Section A 1a-2d)', '英语', '七年级', '人教版Go For It!', '新授课',
        '{"objectives":[{"type":"语言能力","content":"掌握并正确运用name、nice、meet等词汇以及Whats your name? / My name is... / Nice to meet you. 等句型进行自我介绍与问候。","standardRef":"课标·英语·语言技能·说"},{"type":"文化意识","content":"了解中西方初次见面问候方式的差异，培养跨文化交际意识。","standardRef":"课标·英语·文化知识·社会交往"},{"type":"学习能力","content":"能在真实语境中主动运用所学句型进行简单交际，养成大胆开口说英语的习惯。","standardRef":"课标·英语·学习策略·交际策略"}],"keyPoints":["自我介绍和询问姓名的重点句型：Whats your name? My name is... / Im... Nice to meet you."],"difficultPoints":["形容词性物主代词my/your/his/her的正确运用，姓名在不同文化中的表达习惯"],"process":[{"stage":"热身导入","duration":5,"activities":"教师与学生互动问候，How are you today? 播放歌曲Hello, Hello! 营造英语氛围。"},{"stage":"词汇呈现","duration":8,"activities":"通过图片和情境展示name、nice、meet、too、Ms.等新词，跟读模仿发音。"},{"stage":"句型操练","duration":15,"activities":"1a看图匹配名字；1b听录音圈名字；结对操练Whats your name? My name is... 角色互换。"},{"stage":"对话学习","duration":10,"activities":"2d对话分角色朗读，引导学生注意初次见面的交际用语Nice to meet you. 的使用场景。"},{"stage":"总结作业","duration":2,"activities":"总结本课时重点句型，布置分层作业。"}],"boardDesign":"Unit 1 My name''s Gina\n\nWhats your name?      My name is... / Im...\nWhats his name?       His name is...\nWhats her name?      Her name is...\nNice to meet you!    Nice to meet you, too!\n\nGreetings → Introductions → Make friends!","homework":[{"level":"基础","items":["抄写本课时重点单词和句型各3遍"]},{"level":"提高","items":["编写3组不同的询问姓名和自我介绍的小对话"]},{"level":"拓展","items":["用英语向家人或朋友做自我介绍，录制30秒音频"]}],"qualityScore":88,"standardCards":[{"ref":"课标·英语·语言知识","content":"掌握问候、介绍和告别等功能意念项目的常见表达法，能在真实语境中恰当运用。"}]}',
        88, 1, 1);

INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (3, 'OBJECTIVE', 0, '{"type":"语言能力","content":"掌握并正确运用自我介绍与问候的重点句型。","standardRef":"课标·英语·语言技能·说"}', '课标·英语·语言技能·说');
INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (3, 'PROCESS', 1, '{"stage":"句型操练","duration":15,"activities":"1a看图匹配；1b听录音；结对操练自我介绍句型。"}', NULL);
INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (3, 'PROCESS', 2, '{"stage":"对话学习","duration":10,"activities":"2d对话分角色朗读，体会交际用语的使用场景。"}', NULL);

-- 物理：牛顿第一定律 八年级
INSERT INTO lesson_plan (id, task_id, user_id, title, subject, grade, textbook, lesson_type, content, quality_score, is_public, status)
VALUES (4, NULL, 1, '牛顿第一定律', '物理', '八年级', '人教版', '新授课',
        '{"objectives":[{"type":"物理观念","content":"理解牛顿第一定律的内容和意义，知道力是改变物体运动状态的原因而非维持运动的原因。","standardRef":"课标·物理·运动和相互作用·力与运动的关系"},{"type":"科学思维","content":"经历伽利略斜面实验的推理过程，体会理想实验这一重要科学方法。","standardRef":"课标·物理·科学探究·科学推理"},{"type":"科学态度与责任","content":"通过对亚里士多德、伽利略、牛顿等科学家的贡献了解，培养科学探索精神。","standardRef":"课标·物理·科学态度与责任·物理学史"}],"keyPoints":["牛顿第一定律的内容：一切物体在没有受到力的作用时，总保持静止状态或匀速直线运动状态"],"difficultPoints":["理解力与运动的关系，理解惯性是物体的固有属性而非力"],"process":[{"stage":"情境导入","duration":5,"activities":"演示：推小车动，不推就停。提问：运动是否需要力来维持？引发亚里士多德与伽利略观点冲突。"},{"stage":"探究实验","duration":15,"activities":"阻力对物体运动的影响实验：同一小车从同一斜面同一高度滑下，分别在毛巾、棉布、木板上滑行，记录距离。引导推理：表面越光滑，阻力越小，运动越远。"},{"stage":"理想推理","duration":8,"activities":"伽利略推理：如果表面绝对光滑，小车将永远运动下去。笛卡尔补充：匀速直线。牛顿总结：牛顿第一定律。"},{"stage":"惯性应用","duration":10,"activities":"演示：抽纸条、拍灰、锤头紧套。分析生活中的惯性现象，区分惯性和力。"},{"stage":"总结作业","duration":2,"activities":"梳理定律内容和研究方法，布置分层作业。"}],"boardDesign":"牛顿第一定律\n\n一、历史争论\n  亚里士多德：力是维持运动的原因 ✗\n  伽利略：运动不需要力维持（理想实验）✓\n  牛顿：总结定律\n\n二、内容：一切物体不受力 → 静止/匀速直线\n  → 力是改变运动状态的原因\n\n三、惯性：物体保持运动状态不变的性质\n  ↓ 一切物体都有惯性（固有属性）\n  应用：紧锤头、拍灰、安全带","homework":[{"level":"基础","items":["教材P19 动手动脑学物理 第1-2题"]},{"level":"提高","items":["用惯性知识解释：为什么汽车急刹车时乘客会向前倾倒？"]},{"level":"拓展","items":["查找资料，了解安全带和安全气囊是如何利用/防止惯性的。"]}],"qualityScore":95,"standardCards":[{"ref":"课标·物理·运动和相互作用","content":"通过实验，认识牛顿第一定律。能用物体的惯性解释自然界和生活中的有关现象。"},{"ref":"课标·物理·科学探究","content":"经历理想实验的推理过程，认识理想实验在物理学研究中的重要作用。"}]}',
        95, 1, 1);

INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (4, 'OBJECTIVE', 0, '{"type":"物理观念","content":"理解牛顿第一定律的内容和意义，知道力是改变物体运动状态的原因。","standardRef":"课标·物理·运动和相互作用·力与运动的关系"}', '课标·物理·运动和相互作用·力与运动的关系');
INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (4, 'PROCESS', 1, '{"stage":"探究实验","duration":15,"activities":"阻力对物体运动的影响实验，引导推理理想情况。"}', NULL);
INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (4, 'PROCESS', 2, '{"stage":"惯性应用","duration":10,"activities":"演示生活中的惯性现象，分析惯性与力的区别。"}', NULL);

-- 语文：三峡 八年级
INSERT INTO lesson_plan (id, task_id, user_id, title, subject, grade, textbook, lesson_type, content, quality_score, is_public, status)
VALUES (5, NULL, 1, '《三峡》第一课时', '语文', '八年级', '人教版', '新授课',
        '{"objectives":[{"type":"文化自信","content":"感受郦道元笔下三峡的壮美风光，体会古人对祖国山河的热爱，增强文化认同感。","standardRef":"课标·语文·文学阅读与创意表达·古诗文阅读"},{"type":"语言运用","content":"积累「阙、曦、御、溯、湍、巘」等文言字词，能借助注释和工具书疏通文意。","standardRef":"课标·语文·语言文字积累与梳理·文言实词"},{"type":"思维能力","content":"理解先总后分、四季特色分明的结构安排，品味作者精炼生动的写景语言。","standardRef":"课标·语文·思辨性阅读与表达·文章结构分析"}],"keyPoints":["疏通文意，感受三峡山高水长、四季各异的壮丽景色"],"difficultPoints":["品味精炼传神的语言，理解写景中蕴含的情感"],"process":[{"stage":"情境导入","duration":5,"activities":"播放三峡风光视频，配上李白《早发白帝城》朗诵。提问：诗中描写的是哪里？引出郦道元《三峡》。"},{"stage":"初读正音","duration":8,"activities":"学生自由朗读，标注生字。教师范读，强调节奏停顿（如：自非/亭午夜分，不见/曦月）。"},{"stage":"疏通文意","duration":15,"activities":"小组合作，借助课下注释疏通第1-2段（山、夏水）。教师点拨重点字词：通假字「阙」、词类活用「奔」「湍」。"},{"stage":"赏析景物","duration":10,"activities":"讨论：三峡的山有什么特点？（连绵、高峻）夏水有什么特点？（汹涌、湍急）作者用了什么手法？（正侧面结合、夸张）"},{"stage":"总结作业","duration":2,"activities":"梳理本节所学：山与夏水的特点及重点字词，布置分层作业。"}],"boardDesign":"三峡  郦道元（北魏·地理学家·《水经注》）\n\n┌ 总写：山——连绵七百里，两岸连山，略无阙处\n│         （正侧面结合、夸张）重岩叠嶂，隐天蔽日\n│\n├ 分写 夏水：襄陵、沿溯阻绝——凶险\n│            朝发白帝，暮到江陵——湍急（侧面/夸张）\n│\n├ 春冬：清荣峻茂 （水清·树荣·山高·草茂）\n│\n└ 秋：林寒涧肃  高猿长啸  哀转久绝——凄婉\n\n结构：先总后分  语言：精炼生动","homework":[{"level":"基础","items":["背诵课文前两段，抄写并翻译重点字词：阙、曦、襄、溯、奔、湍"]},{"level":"提高","items":["用自己的话描述「夏水襄陵，沿溯阻绝」「虽乘奔御风，不以疾也」所展现的画面，300字左右"]},{"level":"拓展","items":["课后阅读《水经注》其他片段或余秋雨《三峡》，与课文进行对比阅读"]}],"qualityScore":93,"standardCards":[{"ref":"课标·语文·古诗文阅读","content":"诵读古代诗词，阅读浅易文言文，能借助注释和工具书理解基本内容。注重积累、感悟和运用，提高自己的欣赏品位。"}]}',
        93, 1, 1);

INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (5, 'OBJECTIVE', 0, '{"type":"文化自信","content":"感受郦道元笔下三峡的壮美风光，体会古人对祖国山河的热爱。","standardRef":"课标·语文·文学阅读与创意表达·古诗文阅读"}', '课标·语文·文学阅读与创意表达·古诗文阅读');
INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (5, 'OBJECTIVE', 1, '{"type":"语言运用","content":"积累文言字词，借助注释和工具书疏通文意。","standardRef":"课标·语文·语言文字积累与梳理·文言实词"}', '课标·语文·语言文字积累与梳理·文言实词');
INSERT INTO lesson_section (lesson_plan_id, section_type, seq, content, standard_ref) VALUES (5, 'PROCESS', 2, '{"stage":"赏析景物","duration":10,"activities":"讨论三峡山与夏水的特点，分析正侧面结合、夸张等手法。"}', NULL);

-- 演示埋点与审核记录
INSERT INTO usage_log (user_id, school_id, action, scene, duration_sec, created_at)
VALUES (1, 1, 'LOGIN', 'APP', 5, DATEADD('DAY', 0, CURRENT_TIMESTAMP));
INSERT INTO usage_log (user_id, school_id, action, scene, duration_sec, created_at)
VALUES (1, 1, 'GENERATE', 'LESSON_PLAN', 95, DATEADD('DAY', -1, CURRENT_TIMESTAMP));
INSERT INTO usage_log (user_id, school_id, action, scene, duration_sec, created_at)
VALUES (1, 1, 'EXPORT', 'LESSON_PLAN', 12, DATEADD('DAY', -1, CURRENT_TIMESTAMP));
INSERT INTO usage_log (user_id, school_id, action, scene, duration_sec, created_at)
VALUES (1, 1, 'GENERATE', 'LESSON_PLAN', 110, DATEADD('DAY', -2, CURRENT_TIMESTAMP));

INSERT INTO content_review_log (task_id, content_type, result, detail)
VALUES (NULL, 'LESSON_PLAN', 'PASS', '自动审核通过：未检出敏感内容');

-- 种子数据占用了显式 ID，重置自增序号避免后续插入冲突
ALTER TABLE school ALTER COLUMN id RESTART WITH 500;
ALTER TABLE sys_user ALTER COLUMN id RESTART WITH 500;
ALTER TABLE kb_document ALTER COLUMN id RESTART WITH 500;
ALTER TABLE kb_chunk ALTER COLUMN id RESTART WITH 500;
ALTER TABLE prompt_template ALTER COLUMN id RESTART WITH 500;
ALTER TABLE lesson_plan ALTER COLUMN id RESTART WITH 500;
ALTER TABLE lesson_section ALTER COLUMN id RESTART WITH 500;
ALTER TABLE usage_log ALTER COLUMN id RESTART WITH 500;
ALTER TABLE content_review_log ALTER COLUMN id RESTART WITH 500;

CREATE TABLE IF NOT EXISTS auth_token (
    token      VARCHAR(64) PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
